server:
  address: 127.0.0.1
  #port: 8080
  protocol_header: x-forwarded-proto
  use-forward-headers: true
  ssl:
      key-store: classpath:keystore.p12
      key-store-password: yhcKey3690
      keyStoreType: PKCS12
      keyAlias: tomcat

spring:
    redis:
      host: 127.0.0.1
      port: 6379
      password: yhcredis
    freemarker:
      #设定ftl文件路径
      template-loader-path: classpath:/templates
      suffix: .ftl
    resources:
      static-locations: classpath:/static/**
    mvc:
      #设定静态文件路径，js,css等
      static-path-pattern: classpath:/static/**
      view:
        prefix: classpath:/templates/
    datasource:
      netcrawldata:
        url: jdbc:mysql://127.0.0.1:3306/netdata?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true
        username: yhc
        password: yhc
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        name: netcrawldata
      systemData:
        url: jdbc:mysql://127.0.0.1:3306/systemdata?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true
        username: yhc
        password: yhc
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        name: systemData
      # 下面为连接池的补充设置，应用到上面所有数据源中

      ##Druid
      # 初始化大小，最小，最大
      druid:
         initial-size: 5
         max-active: 10
         min-idle: 5
      # 配置获取连接等待超时的时间
         max-wait: 60000
      # 打开PSCache，并且指定每个连接上PSCache的大小
         pool-prepared-statements: true
         max-pool-prepared-statement-per-connection-size: 20
      #druid.max-open-prepared-statements:  #和上面的等价
         validation-query: SELECT 1 FROM DUAL
         validation-query-timeout: 60000
         test-on-borrow: false
         test-on-return: false
         test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
         time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
         min-evictable-idle-time-millis: 100000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      #druid.max-evictable-idle-time-millis:
         filters: stat,wall,log4j
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
         web-stat-filter:
            enabled: true
            url-pattern: /*
            exclusions: /*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
            session-stat-enable: true
            session-stat-max-count: 1000
            principal-session-name:
            principal-cookie-name:
            profile-enable: true
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
         stat-view-servlet:
           enabled: true
           url-pattern: /druid/*
           reset-enable: true
           login-username: druid
           login-password: druid
           allow: 127.0.0.1
           deny:
      # 配置StatFilter
         filter:
           stat:
             db-type: mysql
             log-slow-sql: true
             slow-sql-millis: 2000
      # 配置WallFilter
           wall:
              enabled: true
              db-type: mysql
              config:
                delete-allow: false
                drop-table-allow: false


mybatis:
  mapper-locations: classpath:mapping/*/*.xml
  type-aliases-package: com.yhc.lifeall.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql


md5:
  password: Y1234H54321C
weixin:
  Token: woshizhangzhiman20140515
  EncodingAESKey: 7PuiV7LhBrF7Y4oTAuXEUjC1OX42s0LBQcQb2qYcZzR
