server:
  address: 127.0.0.1
  port: 8080
  server:
    protocol_header: x-forwarded-proto
  use-forward-headers: true

spring:
    freemarker:
      #设定ftl文件路径
      template-loader-path: classpath:/templates
      suffix: .ftl
    resources:
      static-locations: classpath:/static/**
    mvc:
      #设定静态文件路径，js,css等
      static-path-pattern: classpath:/static/**
      view:
        prefix: classpath:/templates/
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/netcrawldata?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true
      username: yhc
      password: Yhc#2018
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yhc.lifeall.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql

